---
- name: Update all packages  # sudo apt update
  apt:
    update_cache: yes
    cache_valid_time: 36000
  become: true


# Install Linux VLAN and eth0.x devices
#
- block:
    - name: Install VLAN
      apt:
        pkg: vlan
        state: present

    - name: Add the 802.1q module  # sudo modprobe 8021q
      modprobe:
        name: 8021q
        state: present

    # Install Linux VLAN devices
    - block:
        - name: Add eth0.x device # sudo vconfig add eth0.x 
          lineinfile:
            path: /etc/network/interfaces.d/vlans
            regexp: '^auto {{ hostvars.gateway.nic_int }}.{{ hostvars[item].ansible_host.split(".")[3] }}'
            line: auto {{ hostvars.gateway.nic_int }}.{{ hostvars[item].ansible_host.split('.')[3] }}
            state: present
            create: true
          loop: '{{ query("inventory_hostnames", "nodes:jetsons") }}'

        - name: Configure eth0.x device
          lineinfile:
            path: /etc/network/interfaces.d/vlans
            regexp: '^iface {{ hostvars.gateway.nic_int }}.{{ hostvars[item].ansible_host.split(".")[3] }}'
            line: "iface {{ hostvars.gateway.nic_int }}.{{ hostvars[item].ansible_host.split('.')[3] }} inet manual"
            state: present
            create: true
          loop: '{{ query("inventory_hostnames", "nodes:jetsons") }}'

        - name: Restart network service  # sudo service networking restart eth0
          ansible.builtin.service:
            name: networking
            state: restarted

  become: true


# Install and configure OVS Bridge
#
- block:
    - name: Install OVS
      apt:
        pkg: 
          - openvswitch-switch 
          - openvswitch-testcontroller 
          - openvswitch-common
        state: present

    - name: Drop OVS Bridge if it exists already  # to achieve a clean state
      openvswitch_bridge:
        bridge: "{{ hostvars.gateway.ifnodes }}"
        state: absent

    - name: Create OVS Bridge  # sudo ovs-vsctl add-br {bridge}  # permanent
      openvswitch_bridge:
        bridge: "{{ hostvars.gateway.ifnodes }}"
        state: present

    - name: Add ports to nodes  # sudo ovs-vsctl add-port {bridge} eth0.x  # permanent
      openvswitch_port:
        bridge: "{{ hostvars.gateway.ifnodes }}"
        port: "{{ hostvars.gateway.nic_int }}.{{ hostvars[item].ansible_host.split('.')[3] }}"
        state: present
      loop: '{{ query("inventory_hostnames", "nodes:jetsons") }}'

    ## Show available ports: sudo ovs-vsctl list-ports o-all
    ## Delete port: sudo ovs-vsctl del-port o-all {port}
    ## https://www.opencloudblog.com/?p=240

    - name: Set static IP address for ovs-vlan-bridge  # sudo ifconfig o-all 10.42.0.1/24
      blockinfile:                                     # sudo ip route add 10.42.0.0/24 dev o-all
        path: /etc/dhcpcd.conf
        marker: "# {mark} OVS-VLAN-BRIDGE"
        block: |
          interface {{ hostvars.gateway.ifnodes }}
          static ip_address={{ hostvars['gateway'].int_cidr }}
      notify: reboot

    - name: Drop static IP address of eth0  # the IP address set via /boot on the SD card
      lineinfile:
        path: /etc/rc.local
        regexp: '^ip addr flush dev {{ hostvars.gateway.nic_int }}'
        line: 'ip addr flush dev {{ hostvars.gateway.nic_int }}'   
        insertbefore: exit 0
        state: present
      notify: reboot

  become: true
