---
- hosts: k3s_single
  roles:
    - {role: 'emu-cfg-edge', tags: 'k3s'}
    - {role: 'k3s-server', tags: 'k3s'}
  vars:
    - k3s:
        bind_address: "{{ emu_ip.split('/')[0] }}"
        cluster_cidr: "10.1.{{ emu_ip.split('/')[0].split('.')[3] }}.0/24"
        service_cidr: "10.2.{{ emu_ip.split('/')[0].split('.')[3] }}.0/24"
