all:
    children:
        gateways:
            hosts:
                gateway:
                    ansible_user: pi
                    nic_ext: wlan0
                    nic_int: eth0
                    host_os: raspberrypi

        nodes:
            hosts:
                node[1:3]:
                node[22:23]:
            
            children:
                k3s_single:
                    hosts: 
                        node22:
                        node23:

        jetsons:
            hosts:
                jetson[1:2]:
