---
# NOTE: Inventory file instead of using group_vars to have all settings in one file.
#
all:
    vars:
        int_cidr: "{{ ansible_host }}/24"

gateways:
    vars:
        ansible_connection: local
        ansible_host: 10.42.0.1  # default gateway address for all nodes
        usevlan: true  # install VLAN interfaces
        ifnodes: "{{ nic_int }}"  # o-all  # interface to access the nodes
        k3s_cidr: 10.41.0.0/16  # cluster-cidr

nodes:
    vars:
        ansible_connection: ssh
        ansible_user: pi
        ansible_pass: raspberry
        ansible_host: "10.42.0.1{{ '%02d'|format(inventory_hostname.split('node')[1]|int) }}"
        emu_k3s_cidr: "10.1.1{{ '%02d'|format(inventory_hostname.split('node')[1]|int) }}.0/24"
        emu_k3s_service_cidr: "10.0.1{{ '%02d'|format(inventory_hostname.split('node')[1]|int) }}.0/24"
    
jetsons:
    vars:
        ansible_connection: ssh
        ansible_user: jetson
        ansible_pass: nano
        ansible_sudo_pass: nano
        ansible_host: "10.42.0.2{{ '%02d'|format(inventory_hostname.split('jetson')[1]|int) }}"
