all:
    vars:
        isAAU: true
        
    children:
        gateways:
            hosts:
                gateway:
                    ansible_user: edge
                    nic_ext: enp5s0
                    nic_int: enp6s0
                    ntp: 143.205.64.56 143.205.64.57
                    host_os: ubuntu

        nodes:
            hosts:
                node[1:31]:
            
        jetsons:
            hosts:
                jetson[1:5]:

        k3s_single:
            hosts: 
                node18:
                node19:

        emu1:
            hosts:
                gateway:
                node16:
                node17:
                node18:
                jetson4:
