all:
    vars:
        isAAU: false
        
    children:
        gateways:
            hosts:
                gateway:
                    ansible_user: pi
                    nic_ext: wlan0
                    nic_int: eth0
                    host_os: raspberrypi

        nodes:
            hosts:
                node[1:3]:
                node[22:23]:
            

        jetsons:
            hosts:
                jetson[1:2]:

        k3s_single:
            hosts: 
                node22:
                node23:
                node3:

        emu1:
            hosts:
                gateway:
                node1:
                node2:
                node22:
                node23:
                node3:
