---
# Clean up OVS-Emu Bridge
#
- block:
    - name: Drop all OVS bridges (except o-all)  # to achieve a clean state
      shell: for bridge in `sudo ovs-vsctl list-br`; do if [ "$bridge" != o-all ]; then sudo ovs-vsctl del-br $bridge; fi; done
      become: true

    - name: Unblock default gateway for nodes (via eth0)  
      shell: iptables -D FORWARD -i {{ hostvars['gateway']['ifnodes'] }} -o {{ hostvars['gateway']['nic_ext'] }} -j DROP
  
  become: true
  when: inventory_hostname == "gateway"


- block:
    - name: Remove all IP addresses from emu interface
      command: "ip addr flush dev eth0.{{ ansible_host.split('.')[3] }}"

    - name: Reset to default gateway 
      command: "ip route replace default via {{ hostvars['gateway'].ansible_host }} dev eth0"

  become: true
  when: not inventory_hostname == "gateway"
