---
# REVIEW c&p from emu-tasks-setup ... correct IP address is required
#
- name: Load variables
  include_vars:
    file: ../../emu-config.yml

- name: Merge emu vars into host information
  set_fact: 
    emu_name: "{{ item.key }}"
    emu_ip: "10.0.{{ emu.hosts[item.key].ip }}"
    emu_mac: "02:00:00:00:{{ emu.hosts[item.key].mac }}"
  when: emu.hosts[item.key].node == ansible_hostname
  loop: '{{ emu.hosts | dict2items }}'

- block:
    - name: Remove all IP addresses from emu interface
      command: "ip addr flush dev eth0.{{ ansible_host.split('.')[3] }}"

    - name: Set IP address on node  # sudo ip addr add 10.0.x.x/16 dev eth0.x
      command: "ip addr add {{ emu_ip }} dev eth0.{{ ansible_host.split('.')[3] }}"

  become: true
  when: not inventory_hostname == "gateway"
