---
- name: Uninstall K3s
  command: /usr/local/bin/k3s-uninstall.sh
  when: "'/usr/local/bin/k3s-uninstall.sh' is file"


# uninstall from server: /usr/local/bin/k3s-uninstall.sh
# uninstall from node:   /usr/local/bin/k3s-agent-uninstall.sh

# uninstall from all nodes: ansible nodes:jetsons -a "/usr/local/bin/k3s-agent-uninstall.sh" --become
