---
# NOTE: Requires emulation vars to be initialized!

- name: Define local vars  # without a separate file
  set_fact:
    edgeFolder: "{{ emuFolder }}/services"

- name: Create edge folders
  file: 
    path: "{{ edgeFolder }}"
    state: directory

- name: Create edge folders (on gateway)
  file: 
    path: "{{ edgeFolder }}"
    state: directory
  delegate_to: 127.0.0.1
  run_once: true

- name: Create K8s edge namespace
  command: kubectl create namespace edge
  register: result
  failed_when:
    - result.rc != 0
    - '"(AlreadyExists)" not in result.stderr'

- name: Set default K8s namespace
  command: kubectl config set-context --current --namespace=edge
  become: true

- name: Copy all K8s edge service configurations to gateway (for SDN Controller)
  template:
    src: "{{ item }}"
    dest: "{{ edgeFolder }}/{{ item | basename }}"
    mode: '0644'
  with_fileglob:
    - templates/*.yml
  delegate_to: 127.0.0.1
  run_once: true
  
- name: Copy all K8s edge service configurations (for convenience)
  template:
    src: "{{ item }}"
    dest: "{{ edgeFolder }}/{{ item | basename }}"
    mode: '0644'
  with_fileglob:
    - templates/*.yml


# - name: Install Nginx K8s service
#   command: "kubectl apply -f {{ edgeFolder }}/at.aau.nginx-host-info.yml --namespace=edge"
