---
# NOTE: Requires emulation vars to be initialized!

- name: Define local vars  # without a separate file
  set_fact:
    edgeFolder: "{{ emuFolder }}/services"

- name: Create edge folders
  file: 
    path: "{{ edgeFolder }}"
    state: directory

- name: Deploy Nginx service configuration for K8s
  template:
    src: edge-nginx.yml
    dest: "{{ edgeFolder }}/edge-nginx.yml"
    mode: '0644'

- name: Install Nginx K8s service
  command: "kubectl apply -f {{ edgeFolder }}/edge-nginx.yml"

