---
emu_public_gateway: cloudgw
emu:
  hosts:
    mobile1:
        ip: 1.100/16
        node: "{{ 'node16' if hostvars.gateway.isAAU else 'node1' }}"
        mac: 01:01
    mobile2: 
        ip: 1.200/16
        node: "{{ 'node17' if hostvars.gateway.isAAU else 'node2' }}"
        mac: 01:02
    edge1: 
        ip: 2.100/16
        node: "{{ 'node18' if hostvars.gateway.isAAU else 'node22' }}"
        mac: 02:01
    edge2: 
        ip: 2.200/16
        node: "{{ 'node19' if hostvars.gateway.isAAU else 'node23' }}"
        mac: 02:02
    cloud: 
        ip: 3.100/16
        node: "{{ 'node15' if hostvars.gateway.isAAU else 'node3' }}"
        mac: 03:01


  switches:
    bs1:
        dpid: 1
        ctrl: tcp:127.0.0.1:6653 # old port: 6633 # default for OpenFlow: 6653
    bs2:
        dpid: 2
        ctrl: tcp:127.0.0.1:6653
    cloudgw:
        dpid: 3


  links:
    - src: bs1
      dest: mobile1
    - src: bs2
      dest: mobile2
    - src: bs1
      dest: edge1
    - src: bs2
      dest: edge2
      delay: 5ms
    - src: bs1
      dest: cloudgw
    - src: bs2
      dest: cloudgw
      delay: 10ms    # only on bs2 so we can test without delay on bs1
    - src: cloudgw
      dest: cloud
