---
- name: Load variables
  include_vars:
    file: "{{ role_name }}-vars.yml"

- name: Define emu folder  # without a separate file
  set_fact:
    emuFolder: /var/emu

- name: Create emu folder
  file:
    path: "{{ emuFolder }}"
    state: directory
    mode: '0755'
    owner: "{{ansible_user}}"
    group: "{{ansible_user}}"
  become: true

- name: Create emu folder on Gateway  
  file:
    path: "{{ emuFolder }}"
    state: directory
    mode: '0755'
    owner: "{{ hostvars['gateway'].ansible_user }}"
    group: "{{ hostvars['gateway'].ansible_user }}"
  become: true
  run_once: true
  delegate_to: 127.0.0.1
  when: "'gateway' not in ansible_play_hosts"

- name: Merge emu vars into host information
  set_fact: 
    emu_name: "{{ item.key }}"
    emu_ip: "10.0.{{ emu.hosts[item.key].ip }}"
  when: emu.hosts[item.key].node == ansible_hostname
  loop: '{{ emu.hosts | dict2items }}'

- block:
    - name: Remove all IP addresses from emu interface
      command: "ip addr flush dev eth0.{{ ansible_host.split('.')[3] }}"

    - name: Set IP address on node  # sudo ip addr add 10.0.x.x/16 dev eth0.x
      command: "ip addr add {{ emu_ip }} dev eth0.{{ ansible_host.split('.')[3] }}"

  become: true
  when: not inventory_hostname == "gateway"
