---
- name: Include setup
  include_tasks: "{{ role_path }}/{{ role_name }}-setup.yml"
  when: cleanup is not defined or not cleanup

- name: Include cleanup
  include_tasks: "{{ role_path }}/{{ role_name }}-cleanup.yml"
  when: cleanup is defined and cleanup
